# Generated by Django 6.0.2 on 2026-02-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_remove_aicalllog_end_time_nursestation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nursestation',
            old_name='room_count',
            new_name='end_room',
        ),
        migrations.AddField(
            model_name='nursestation',
            name='start_room',
            field=models.IntegerField(default=1),
        ),
    ]
