# Generated by Django 6.0.2 on 2026-02-17 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_rename_room_count_nursestation_end_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicalllog',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_api.nursestation'),
        ),
    ]
