# Generated by Django 6.0.2 on 2026-02-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_alter_aicalllog_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicalllog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
