# Generated by Django 6.0.2 on 2026-02-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_aicalllog_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aicalllog',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='aicalllog',
            name='station',
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
