# Generated by Django 6.0.2 on 2026-02-22 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_remove_aicalllog_start_time_remove_aicalllog_station_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aicalllog',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
