# Generated by Django 6.0.2 on 2026-02-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_remove_aicalllog_updated_at_aicalllog_cleared_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelReport',
            fields=[
            ],
            options={
                'verbose_name': '📥 Download Excel (CSV)',
                'verbose_name_plural': '📥 Download Excel (CSV)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core_api.aicalllog',),
        ),
    ]
