# Generated by Django 6.0.2 on 2026-02-24 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0008_excelreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('priority_level', models.CharField(choices=[('1', 'Critical (ከፍተኛ አደጋ)'), ('2', 'Urgent (አስቸኳይ)'), ('3', 'Normal (መደበኛ)')], default='3', max_length=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_api.nursestation'),
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
