# Generated by Django 6.0.2 on 2026-02-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0009_patientstatus_aicalllog_station_aicalllog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicalllog',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='bed_number',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
