# Generated by Django 6.0.3 on 2026-03-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0010_aicalllog_arrived_at_aicalllog_bed_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicalllog',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
    ]
