# Generated by Django 6.0.4 on 2026-05-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0011_aicalllog_is_escalated'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicalllog',
            name='call_type',
            field=models.CharField(default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aicalllog',
            name='room_number',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='SpecialRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_id', models.CharField(help_text='ለምሳሌ ER1', max_length=50, unique=True)),
                ('regular_id', models.CharField(help_text='ለምሳሌ RR1', max_length=50, unique=True)),
                ('room_name_display', models.CharField(help_text='ዳሽቦርድ ላይ የሚታየው ስም (ለምሳሌ OR BED 1)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emergency_stations', models.ManyToManyField(blank=True, related_name='emergency_mapping', to='core_api.nursestation')),
                ('regular_stations', models.ManyToManyField(blank=True, related_name='regular_mapping', to='core_api.nursestation')),
            ],
        ),
    ]
