# Generated by Django 6.0.4 on 2026-05-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0012_aicalllog_call_type_aicalllog_is_acknowledged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicalllog',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
