# Generated by Django 6.0.4 on 2026-05-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0013_aicalllog_acknowledged_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aicalllog',
            name='station',
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='stations',
            field=models.ManyToManyField(blank=True, related_name='call_logs', to='core_api.nursestation'),
        ),
    ]
