# Generated by Django 6.0.4 on 2026-05-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0014_remove_aicalllog_station_aicalllog_stations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aicalllog',
            name='is_escalated',
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='aicalllog',
            name='bed_number',
            field=models.CharField(default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='aicalllog',
            name='call_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Critical', 'Critical')], default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='aicalllog',
            name='room_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='aicalllog',
            name='stations',
            field=models.ManyToManyField(related_name='calls', to='core_api.nursestation'),
        ),
    ]
