# Generated by Django 6.0.4 on 2026-05-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0015_remove_aicalllog_is_escalated_aicalllog_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicalllog',
            name='is_special_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aicalllog',
            name='call_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Critical', 'Critical'), ('Emergency', 'Emergency'), ('Regular', 'Regular')], default='Normal', max_length=20),
        ),
    ]
