# Generated by Django 6.0.4 on 2026-05-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0016_aicalllog_is_special_call_alter_aicalllog_call_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=100, null=True)),
                ('twilio_from_number', models.CharField(blank=True, max_length=20, null=True)),
                ('notification_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('escalation_delay_seconds', models.IntegerField(default=30)),
            ],
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
    ]
