# Generated by Django 6.0.4 on 2026-05-04 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0017_systemsettings_aicalllog_is_escalated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('nurse_id', models.CharField(max_length=2, unique=True)),
                ('rfid_uid', models.CharField(help_text='NFC Card UID', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_calls', to='core_api.nurse'),
        ),
        migrations.AddField(
            model_name='nursestation',
            name='nurses',
            field=models.ManyToManyField(blank=True, related_name='stations', to='core_api.nurse'),
        ),
    ]
