# Generated by Django 6.0.4 on 2026-05-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0018_nurse_aicalllog_responded_by_nursestation_nurses'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
