# Generated by Django 6.0.4 on 2026-08-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0019_nurse_email_nurse_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicalllog',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aicalllog',
            name='call_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Critical', 'Critical'), ('Emergency', 'Emergency'), ('Regular', 'Regular'), ('AI_FALL', 'AI Fall Detected'), ('AI_TREMOR', 'AI Tremor / Seizure')], default='Normal', max_length=30),
        ),
        migrations.AlterField(
            model_name='nursestation',
            name='station_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='patientstatus',
            name='priority_level',
            field=models.CharField(choices=[('1', 'Critical (High Priority)'), ('2', 'Urgent'), ('3', 'Normal')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='specialroom',
            name='emergency_id',
            field=models.CharField(help_text='e.g. ER1', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='specialroom',
            name='regular_id',
            field=models.CharField(help_text='e.g. RR1', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='specialroom',
            name='room_name_display',
            field=models.CharField(help_text='Display name on dashboard (e.g. OR BED 1)', max_length=100, unique=True),
        ),
    ]
