# Generated by Django 6.0.4 on 2026-08-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0020_aicalllog_notes_alter_aicalllog_call_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicalllog',
            name='location_type',
            field=models.CharField(default='ROOM', help_text='e.g. ROOM, CORRIDOR, STAIRS, WAITING_AREA', max_length=50),
        ),
        migrations.AlterField(
            model_name='aicalllog',
            name='bed_number',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='aicalllog',
            name='room_number',
            field=models.CharField(max_length=50),
        ),
    ]
