# Generated by Django 6.0.4 on 2026-08-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0021_aicalllog_location_type_alter_aicalllog_bed_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenter_name', models.CharField(default='MedPulse Smart-Care AI', max_length=150)),
                ('event_name', models.CharField(default='Hospital Innovation & Investor Pitch Deck', max_length=200)),
                ('tagline', models.CharField(default='Transforming Inpatient Safety & Clinical Operations with Edge AI & IoT', max_length=255)),
                ('contact_email', models.CharField(default='contact@medpulse-ai.com', max_length=100)),
                ('contact_phone', models.CharField(default='+251 911 000000', max_length=50)),
                ('contact_website', models.CharField(default='https://medpulse-ai.com', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '🎯 Presentation Settings',
                'verbose_name_plural': '🎯 Presentation Settings',
            },
        ),
        migrations.CreateModel(
            name='PitchSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, help_text='Slide display order (1, 2, 3...)')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('slide_type', models.CharField(choices=[('HERO', '1. Hero & Hook'), ('PROBLEM', '2. Problem & Pain Points'), ('SOLUTION', '3. Solution & Innovation'), ('ARCHITECTURE', '4. Hardware & System Architecture'), ('LIVE_DEMO', '5. Interactive Live Demo'), ('ROI_IMPACT', '6. Hospital ROI & Impact'), ('ADVANTAGES', '7. Competitive Advantages'), ('TEAM_CTA', '8. Business Model & Call to Action'), ('CUSTOM', 'Custom Slide')], default='CUSTOM', max_length=30)),
                ('badge', models.CharField(default='INNOVATION', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('icon_name', models.CharField(default='local_hospital', help_text='Material Symbol icon name or emoji', max_length=50)),
                ('bullets_json', models.JSONField(blank=True, default=list, help_text='List of cards/bullets: [{icon, title, desc, tag}]')),
                ('stats_json', models.JSONField(blank=True, default=list, help_text='List of stats: [{value, label, subtext}]')),
                ('image_url', models.CharField(blank=True, help_text='Optional diagram or photo URL', max_length=500, null=True)),
                ('demo_config', models.JSONField(blank=True, default=dict, help_text='Config for live simulation widgets')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '📽️ Pitch Slide',
                'verbose_name_plural': '📽️ Pitch Slides',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='excelreport',
            options={'verbose_name': '📥 Download Excel (CSV Report)', 'verbose_name_plural': '📥 Download Excel (CSV Report)'},
        ),
    ]
