# Generated by Django 6.0.4 on 2026-08-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0022_pitchsetting_pitchslide_alter_excelreport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchsetting',
            name='camera_image',
            field=models.CharField(blank=True, default='/static/images/medpulse_camera_node.jpg', help_text='AI Camera photo URL', max_length=500),
        ),
        migrations.AddField(
            model_name='pitchsetting',
            name='demo_video_title',
            field=models.CharField(blank=True, default='MedPulse Live Hardware & Edge AI Demo', max_length=200),
        ),
        migrations.AddField(
            model_name='pitchsetting',
            name='demo_video_url',
            field=models.CharField(blank=True, default='https://www.youtube.com/embed/dQw4w9WgXcQ', help_text='YouTube embed, Vimeo URL, or Direct MP4 link', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pitchsetting',
            name='product_3d_title',
            field=models.CharField(blank=True, default='MedPulse Smart Station 3D Interactive Model', max_length=200),
        ),
        migrations.AddField(
            model_name='pitchsetting',
            name='product_image',
            field=models.CharField(blank=True, default='/static/images/medpulse_smart_device.jpg', help_text='Product photo URL', max_length=500),
        ),
        migrations.AddField(
            model_name='pitchslide',
            name='product_3d_enabled',
            field=models.BooleanField(default=False, help_text='Enable 3D interactive rotation on this slide'),
        ),
        migrations.AddField(
            model_name='pitchslide',
            name='video_url',
            field=models.CharField(blank=True, help_text='Optional video URL (YouTube/MP4)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pitchslide',
            name='slide_type',
            field=models.CharField(choices=[('HERO', '1. Hero & Hook'), ('PROBLEM', '2. Problem & Pain Points'), ('SOLUTION', '3. Solution & Innovation'), ('ARCHITECTURE', '4. Hardware & System Architecture'), ('PRODUCT_3D', '5. 3D Product & Hardware Inspection'), ('LIVE_DEMO', '6. Interactive Live Demo'), ('VIDEO_DEMO', '7. Live Hardware & AI Video'), ('ROI_IMPACT', '8. Hospital ROI & Impact'), ('ADVANTAGES', '9. Competitive Advantages'), ('TEAM_CTA', '10. Business Model & Call to Action'), ('CUSTOM', 'Custom Slide')], default='CUSTOM', max_length=30),
        ),
    ]
