# Generated by Django 6.0.4 on 2026-08-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0023_pitchsetting_camera_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchslide',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Upload custom slide photo from computer', null=True, upload_to='pitch_slides/'),
        ),
        migrations.AddField(
            model_name='pitchslide',
            name='image_layout',
            field=models.CharField(choices=[('RIGHT_SPLIT', 'Right Split Photo (UltiMedic Style)'), ('ROUND_MASK', 'Circular Doctor/Device Frame (UltiMedic Style)'), ('FLOATING_CARD', 'Floating Card Frame'), ('HERO_BANNER', 'Hero Wide Photo Banner'), ('NONE', 'No Image')], default='RIGHT_SPLIT', help_text='Visual presentation layout for images on this slide', max_length=30),
        ),
        migrations.AddField(
            model_name='pitchslide',
            name='secondary_image_file',
            field=models.ImageField(blank=True, help_text='Upload secondary photo', null=True, upload_to='pitch_slides/'),
        ),
    ]
