# Generated by Django 6.0.4 on 2026-09-21 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0024_pitchslide_image_file_pitchslide_image_layout_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PitchSetting',
        ),
        migrations.DeleteModel(
            name='PitchSlide',
        ),
    ]
