# Generated by Django 6.0.4 on 2026-09-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0025_delete_pitchsetting_delete_pitchslide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelReport',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tts_language',
            field=models.CharField(choices=[('am', 'አማርኛ (Amharic)'), ('en', 'English')], default='am', max_length=10, verbose_name='AI Voice Announcement Language'),
        ),
    ]
